alpha: 1.0
bandwidth: '[1.0]'
dataname: MUTAG
dis_gamma: 10.0
encoder_equal_dim: true
epochs: 10
gcn_num_layer: 2
log_code: use_edge_attr_2
max_norm: 0.0001
model: vanilla
normalization: null
objective_fuc: SCL
only_node_attr: false
step_size: 0.1
use_edge_attr: true
weight_decay: 0.0
