alpha: 0.1
bandwidth: '[1.0]'
dataname: PTC_FM
dis_gamma: 1.0
encoder_equal_dim: true
epochs: 10
gcn_num_layer: 2
max_norm: 0.0001
model: vanilla
normalization: null
objective_fuc: UCL
only_node_attr: true
step_size: 0.1
weight_decay: 0.0
